export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE'

// Project
export const NEW_PROJECT_REQUEST = 'NEW_PROJECT_REQUEST'
export const NEW_PROJECT_SUCCESS = 'NEW_PROJECT_SUCCESS'
export const NEW_PROJECT_FAILURE = 'NEW_PROJECT_FAILURE'

export const GET_ALL_PROJECT_REQUEST = 'GET_ALL_PROJECT_REQUEST'
export const GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS'
export const GET_ALL_PROJECT_FAILURE = 'GET_ALL_PROJECT_FAILURE'

export const GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST'
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS'
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE'

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST'
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS'
export const UPDATE_PROJECT_DETAILS_FAILURE = 'UPDATE_PROJECT_DETAILS_FAILURE'

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'

// User
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// Account
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE'

//Invoice
export const NEW_INVOICE_REQUEST = 'NEW_INVOICE_REQUEST'
export const NEW_INVOICE_SUCCESS = 'NEW_INVOICE_SUCCESS'
export const NEW_INVOICE_ERROR = 'NEW_INVOICE_ERROR'

export const GET_ALL_INVOICE_REQUEST = 'GET_ALL_INVOICE_REQUEST'
export const GET_ALL_INVOICE_SUCCESS = 'GET_ALL_INVOICE_SUCCESS'
export const GET_ALL_INVOICE_ERROR = 'GET_ALL_INVOICE_ERROR'

export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST'
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS'
export const GET_INVOICE_ERROR = 'GET_INVOICE_ERROR'

export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE'

//GET ALL Client

export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST'
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS'
export const GET_ALL_CLIENTS_ERROR = 'GET_ALL_CLIENTS_ERROR'

//GET CLIENT

export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST'
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS'
export const GET_CLIENT_ERROR = 'GET_CLIENT_ERROR'

//ADD CLIENT

export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR'
//PortFolio
export const UPDATE_PORTFOLIO_FOLDER = 'UPDATE_PORTFOLIO_FOLDER'
export const UPDATE_PORTFOLIO_FOLDER_SUCCESS = 'UPDATE_PORTFOLIO_FOLDER_SUCCESS'
export const UPDATE_PORTFOLIO_FOLDER_FAILURE = 'UPDATE_PORTFOLIO_FOLDER_FAILURE'

export const GET_PORTFOLIO_FOLDER_REQUEST = 'GET_PORTFOLIO_FOLDER_REQUEST'
export const GET_PORTFOLIO_FOLDER_SUCCESS = 'GET_PORTFOLIO_FOLDER_SUCCESS'
export const GET_PORTFOLIO_FOLDER_FAILURE = 'GET_PORTFOLIO_FOLDER_FAILURE'

export const DELETE_PORTFOLIO_FOLDER = 'DELETE_PORTFOLIO_FOLDER'
export const DELETE_PORTFOLIO_FOLDER_SUCCESS = 'DELETE_PORTFOLIO_FOLDER_SUCCESS'
export const DELETE_PORTFOLIO_FOLDER_FAILURE = 'DELETE_PORTFOLIO_FOLDER_FAILURE'

//send mail

export const SEND_EMAIL_REQUEST='SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS='SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_ERROR='SEND_EMAIL_ERROR'

// mail Templates

export const GET_ALL_MAIL_TEMPLATES_REQUEST='GET_ALL_MAIL_TEMPLATES_REQUEST'
export const GET_ALL_MAIL_TEMPLATES_SUCCESS='GET_ALL_MAIL_TEMPLATES_SUCCESS'
export const GET_ALL_MAIL_TEMPLATES_ERROR='GET_ALL_MAIL_TEMPLATES_ERROR'


//revision in invoice
export const SEND_REVISION_REQUEST='SEND_REVISION_REQUEST'
export const SEND_REVISION_SUCCESS='SEND_REVISION_SUCCESS'
export const SEND_REVISION_ERROR='SEND_REVISION_ERROR'

export const GET_ALL_INVOICE_CONVERSATION_REQUEST='GET_ALL_INVOICE_CONVERSATION_REQUEST'
export const GET_ALL_INVOICE_CONVERSATION_SUCCESS='GET_ALL_INVOICE_CONVERSATION_SUCCESS'
export const GET_ALL_INVOICE_CONVERSATION_ERROR='GET_ALL_INVOICE_CONVERSATION_ERROR'


export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO'
export const UPDATE_PORTFOLIO_SUCCESS = 'UPDATE_PORTFOLIO_SUCCESS'
export const UPDATE_PORTFOLIO_FAILURE = 'UPDATE_PORTFOLIO_FAILURE'

export const GET_PORTFOLIO_REQUEST = 'GET_PORTFOLIO_REQUEST'
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'
export const GET_PORTFOLIO_FAILURE = 'GET_PORTFOLIO_FAILURE'

export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO'
export const DELETE_PORTFOLIO_SUCCESS = 'DELETE_PORTFOLIO_SUCCESS'
export const DELETE_PORTFOLIO_FAILURE = 'DELETE_PORTFOLIO_FAILURE'
