export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE'

// Project
export const NEW_PROJECT_REQUEST = 'NEW_PROJECT_REQUEST'
export const NEW_PROJECT_SUCCESS = 'NEW_PROJECT_SUCCESS'
export const NEW_PROJECT_FAILURE = 'NEW_PROJECT_FAILURE'

export const GET_ALL_PROJECT_REQUEST = 'GET_ALL_PROJECT_REQUEST'
export const GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS'
export const GET_ALL_PROJECT_FAILURE = 'GET_ALL_PROJECT_FAILURE'

export const USER_IS_ON_UPDATE_SCREEN = 'USER_IS_ON_UPDATE_SCREEN'

export const GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST'
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS'
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE'

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST'
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS'
export const UPDATE_PROJECT_DETAILS_FAILURE = 'UPDATE_PROJECT_DETAILS_FAILURE'

// User
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// Account
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE'

//Invoice
export const NEW_INVOICE_REQUEST = 'NEW_INVOICE_REQUEST'
export const NEW_INVOICE_SUCCESS = 'NEW_INVOICE_SUCCESS'
export const NEW_INVOICE_ERROR = 'NEW_INVOICE_ERROR'

export const GET_INVOICE_REQUEST= 'GET_INVOICE_REQUEST'
export const GET_INVOICE_SUCCESS= 'GET_INVOICE_SUCCESS'
export const GET_INVOICE_ERROR= 'GET_INVOICE_ERROR'


export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE'

//PortFolio
export const UPDATE_PORTFOLIO_FOLDER = 'UPDATE_PORTFOLIO_FOLDER'
export const UPDATE_PORTFOLIO_FOLDER_SUCCESS = 'UPDATE_PORTFOLIO_FOLDER_SUCCESS'
export const UPDATE_PORTFOLIO_FOLDER_FAILURE = 'UPDATE_PORTFOLIO_FOLDER_FAILURE'

export const GET_PORTFOLIO_FOLDER_REQUEST = 'GET_PORTFOLIO_FOLDER_REQUEST'
export const GET_PORTFOLIO_FOLDER_SUCCESS = 'GET_PORTFOLIO_FOLDER_SUCCESS'
export const GET_PORTFOLIO_FOLDER_FAILURE = 'GET_PORTFOLIO_FOLDER_FAILURE'

export const DELETE_PORTFOLIO_FOLDER = 'DELETE_PORTFOLIO_FOLDER'
export const DELETE_PORTFOLIO_FOLDER_SUCCESS = 'DELETE_PORTFOLIO_FOLDER_SUCCESS'
export const DELETE_PORTFOLIO_FOLDER_FAILURE = 'DELETE_PORTFOLIO_FOLDER_FAILURE'